#!/bin/bash
apt-get update
apt-get install jq -y

wget https://github.com/wildlife-systems/sensor-control/raw/main/sc-prototype
chown root:root sc-prototype
chmod +x sc-prototype
mv sc-prototype /usr/bin

wget https://github.com/wildlife-systems/sensor-control/raw/main/sensor-onboard
chown root:root sensor-onboard
chmod +x sensor-onboard
mv sensor-onboard /usr/bin

sudo mkdir -p /var/aao/sensors
sudo touch /var/aoo/sensors/onboard

wget https://github.com/wildlife-systems/sensor-control/raw/main/sr
chown root:root sr
chmod +x sr
mv sr /usr/bin
