#!/bin/bash

# WildlifeSystems
#
# This script is part of the WildlifeSystems project. For further information
# please refer to https://docs.wildlife.systems, or for more information on
# the project itself, please refer to https://wildlife.systems.

# Check we are running as root
if [ "$(id -u)" -ne 0 ]; then
    echo "This script must be run as root" 1>&2
    exit 1
fi

# First argument to this script is the name of the sensor to install
SENSOR=$1

if [ -z "$SENSOR" ]; then
    echo "Usage: $0 <sensor-name>"
    exit 1
fi

wget -O install-$SENSOR https://raw.githubusercontent.com/Wildlife-Systems/sensor-$SENSOR/main/install
 if [ $? -ne 0 ]; then
    echo "Failed to download install script for $SENSOR"
    rm install-$SENSOR
    exit 1
fi

chmod +x install-$SENSOR
./install-$SENSOR
if [ $? -ne 0 ]; then
    echo "Failed to run install script for $SENSOR"
    rm install-$SENSOR
    exit 1
fi

rm install-$SENSOR
