#!/bin/bash

# WildlifeSystems
#
# This script is part of the WildlifeSystems project. For further information
# please refer to https://docs.wildlife.systems, or for more information on
# the project itself, please refer to https://wildlife.systems.

JSON='{"sensor":null,"measures":null,"value":null,"unit":null,"node_id":null,"sensor_id":null,"timestamp":null,"config":null}'
echo $JSON
